# config/mappings.yaml

connections:
  - trello:
      board_id: TRELLO_BOARD_ORGANNACT
      api_key: TRELLO_API_KEY
      token: TRELLO_TOKEN
    jira:
      project_key: JIRA_PROJECT_KEY
      host: JIRA_URL
      user: JIRA_USER
      api_token: JIRA_API_TOKEN
      customfield_trello_id: customfield_10000  # Campo personalizado do Jira para armazenar o ID do card do Trello
    sync:
      interval: "*/5 * * * *"  # Cron expression every 5 minutes
      fields:
        - title
        - description
        - checklists
        - comments
        - attachments

