# config/mappings.yaml

connections:
  - trello:
      board_id: ${{ secrets.TRELLO_BOARD_ORGANNACT }}
      api_key: ${{ secrets.TRELLO_API_KEY }}
      token: ${{ secrets.TRELLO_TOKEN }}
    jira:
      project_key: ${{ secrets.JIRA_PROJECT_KEY }}
      host: ${{ secrets.JIRA_HOST }}
      user: ${{ secrets.JIRA_USER }}
      api_token: ${{ secrets.JIRA_API_TOKEN }}
      customfield_trello_id: customfield_10000  # Campo personalizado do Jira para armazenar o ID do card do Trello
    sync:
      interval: "*/5 * * * *"  # Cron expression every 5 minutes
      fields:
        - title
        - description
        - checklists
        - comments
        - attachments

