name: "Multi-Board Sync"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      connections: ${{ steps.parse.outputs.connections }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install parsing dependencies
        run: |
          pip install pyyaml jq
      - name: Parse mappings
        id: parse
        run: |
          python - <<EOF
          import yaml, json
          m = yaml.safe_load(open('config/mappings.yaml'))['connections']
          out = []
          for i, c in enumerate(m):
              c['index'] = i
              out.append(c)
          print('::set-output name=connections::' + json.dumps(out))
          EOF

  sync:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        connection: ${{ fromJson(needs.setup.outputs.connections) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run sync for connection
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd)/src python src/workers/connection_worker.py --config config/mappings.yaml --connection-index ${{ matrix.connection.index }}
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
          TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_BOARD_ORGANNACT: ${{ secrets.TRELLO_BOARD_ORGANNACT }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
