name: "Multi-Board Sync"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      connections: ${{ steps.parse.outputs.connections }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install parsing dependencies
        run: |
          pip install pyyaml jq
      - name: Parse mappings
        id: parse
        run: |
          python - <<EOF
          import yaml, json
          m = yaml.safe_load(open('config/mappings.yaml'))['connections']
          print('::set-output name=connections::' + json.dumps(m))
          EOF

  sync:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        connection: ${{ fromJson(needs.setup.outputs.connections) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run sync for connection
        run: |
          python src/workers/connection_worker.py --config config/mappings.yaml --connection-index ${{ matrix.connection_index }}
        env:
          TRELLO_CLIENT_ID: ${{ secrets[matrix.connection.trello.client_id] }}
          TRELLO_CLIENT_SECRET: ${{ secrets[matrix.connection.trello.client_secret] }}
          TRELLO_ACCESS_TOKEN: ${{ secrets[matrix.connection.trello.access_token] }}
          TRELLO_REFRESH_TOKEN: ${{ secrets[matrix.connection.trello.refresh_token] }}
          JIRA_URL: ${{ matrix.connection.jira.host }}
          JIRA_USER: ${{ secrets[matrix.connection.jira.user] }}
          JIRA_API_TOKEN: ${{ secrets[matrix.connection.jira.api_token] }}
